### ISSUE TITLE
Default values not applied to bunsen form when array items added

### ISSUE THREAD

**Issue by cbeekciena** [ciena-frost/ember-frost-bunsen#185] opened 2016-09-13 21:41 UTC
When you add default values to properties of array items defaults are not applied. This can be seen with the following example.

Note:  The first array item added does not have the default value but subsequent values do.  This is reproducible in the live-editor.

**Model**

```json
{
  "properties": {
    "foo": {
      "items": {
        "properties": {
          "bar": {
            "default": "test",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    }
  },
  "type": "object"
}
```

**View**
```json
{
  "version": "2.0",
  "type": "form",
  "cells": [
    {
      "extends": "main"
    }
  ],
  "cellDefinitions": {
    "item": {
      "children": [
        {
          "model": "bar"
        }
      ]
    },
    "main": {
      "children": [
        {
          "model": "foo",
          "arrayOptions": {
            "itemCell": {
              "extends": "item",
              "label": "Foo"
            }
          }
        }
      ]
    }
  }
}
```

You can reproduce this issue in the [live editor](http://ciena-frost.github.io/ember-frost-bunsen/#/editor).

**Comment by sandersky** [comment] 2016-09-25 02:36
Duplicate of #174

**Closed by sandersky** 2016-09-25 02:36 UTC
Labels: bug
