### ISSUE TITLE
Bug: Default values are not populated in select box and frost field if there are conditions on page

### ISSUE THREAD

**Issue by sunilzkumar** [ciena-frost/ember-frost-bunsen#463] opened 2017-08-01 10:29 UTC
Default values are not populated in select box and frost field even if they are present in the model if there are conditional rendering on the page.

I see a similar bug fix in the change logs as below:

12.2.3
Fixed a bug where conditions evaluated on the default value don't trigger the renderModel CP. The CP was unnecessary and removing it fixed the issue.

I am on version 14.23.7 but still I am seeing this issue. Please check. Looks like it got reintroduced or something.

**Comment by sophypal** [comment] 2017-08-01 15:22
Duplicate of https://github.com/ciena-frost/ember-frost-bunsen/issues/139

**Closed by sophypal** 2017-08-01 15:22 UTC
