### ISSUE TITLE
Modal query field value is getting refreshed on selection of values from a field that has been used in a bunsen condition on another field.

### ISSUE THREAD

**Issue by goforsatish** [ciena-frost/ember-frost-bunsen#536] opened 2018-07-06 07:43 UTC
Are you opening a **BUG REPORT** or a **FEATURE REQUEST / CODE CHANGE**?

There is a section for each below.  Please complete the appropriate section and remove the other one.

We realize there is a lot of data requested here. We ask only that you do your best to provide as much information as possible so we can better help you.

# BUG REPORT

* [x] I have ensured that the issue isn't already reported
* [x] I have confirmed that the issue is reproducible with the latest released version
* [x] I have deleted the **FEATURE REQUEST / CODE CHANGE** section

## Summary
For example :  if there are four fields on forms, let’s say field1, field2, field3 and field4. Field4 has a modal query on value change of field3, whereas field2 there is a bunsen condition that makes this field visible/invisible on form on field1 values change. When user selects any values from field3 a modal query call is made to populate values on field4. If user selects any value from field1 the modal query on field4 is getting triggered  again and field4 value is getting refreshed.

## Expected Behavior
Modal query field value only should get changed on value change of its onselect field.
## Actual Behavior
For example :  if there are four fields on forms, let’s say field1, field2, field3 and field4. Field4 has a modal query on value change of field3, whereas field2 there is a bunsen condition that makes this field visible/invisible on form on field1 values change. When user selects any values from field3 a modal query call is made to populate values on field4. If user selects any value from field1 the modal query on field4 is getting triggered  again and field4 value is getting refreshed.

## Possible Solution
* Not obligatory, but suggest a fix/reason for the bug

## Steps to Reproduce
if there are four fields on forms, let’s say field1, field2, field3 and field4. Field4 has a modal query on value change of field3, whereas field2 there is a bunsen condition that makes this field visible/invisible on form on field1 values change. When user selects any values from field3 a modal query call is made to populate values on field4. If user selects any value from field1 the modal query on field4 is getting triggered  again and field4 value is getting refreshed.

---

* [ ] Include the contents of your _package.json_ file
* [ ] Steps to reproduce:
  1.
  2.
  3.
  4.
  ...

## Context
* How has this issue affected you? What are you trying to accomplish?
* Providing context helps us come up with a solution that is most useful in the real world.

## Environment

(answer all that are applicable)

* [ ] I am using the latest released version (can check with `npm ls <package-name>`)
* I am using these browsers:
  * [ ] Latest Chrome
  * [ ] Latest Firefox
* [ ] My version of `Node` is:
* [ ] My version of `npm` is:
* [ ] My OS is:
* [ ] Include the contents of your _package.json_ file

**Comment by sophypal** [comment] 2018-07-06 15:37
@goforsatish While I don't fully comprehend the breadth of your summary, I think I get the gist. For example, what is a modal query?

I'm inclined to say that this is as designed since conditions results in brand new schema being generated which causes

- _a) component being destroyed_ 
- _b) component being recreated_

It is as designed according to that definition but I realize it's a bad design. So I'm closing this because this is not a bug but this behavior is not ideal and I understand your frustration. If this `refreshing` of your component state is a problem, try to make your renderers more deterministic as to depend on the state of the form vs the state of the component.

**Closed by sophypal** 2018-07-06 15:37 UTC
