### ISSUE TITLE
The renderer for the date time input needs to store the state in the model

### ISSUE THREAD

**Issue by d-ashfield** [ciena-frost/ember-frost-bunsen#480] opened 2017-10-27 17:11 UTC
The 'when' renderer for the date time input needs to store the state in the model (assumes fixes have been done in ember-frost-date-picker to allow it to accept a selection property/value - https://github.com/ciena-frost/ember-frost-date-picker/issues/72).

This is becoming a blocking issue in the mcp provisioning forms, where we need to use bunsen conditionals that force a re-render on the forms.  When a re-render occurs the time is being reset back to the defaults of 'Now' or 'Never'.

**Comment by notmessenger** [comment] 2017-10-31 13:23
@d-ashfield Do you mean to refer to the `when` renderer - http://ciena-frost.github.io/ember-frost-bunsen/#/view/renderers?renderer=when - and not the `datetime` one as you have written - http://ciena-frost.github.io/ember-frost-bunsen/#/view/renderers?renderer=datetime ?

**Comment by d-ashfield** [comment] 2017-10-31 14:53
Sorry, yes, I meant the 'when' renderer in bunsen.

**Comment by notmessenger** [comment] 2017-11-01 15:58
The `when` renderer - http://ciena-frost.github.io/ember-frost-bunsen/#/view/renderers?renderer=when - has a required `value` property that can be set to any desired initial value which is stored on the model

**Comment by sophypal** [comment] 2017-11-01 16:29
So the problem isn't that the value is not store. The problem is that for a few renderers, the exact state of the component can't be expressed in the bunsen value. Meaning, some renderers are not stateless since they rely on some temporary and internal property that gets wiped out when things get destroyed and re-rendered.

**Comment by sophypal** [comment] 2017-11-01 16:33
After careful considering, this is not an issue that has a easy solution. I'll have to think about it more.

**Comment by notmessenger** [comment] 2017-11-01 16:35
This component has been functioning correctly since it was introduced Mar 28, 2017.   The only changes to it that raised my eyebrows were on Sep 12 but I reverted those changes and the described issue in our consuming application was not remedied.   I am very unknowledgeable with this repo but it seems that the problem does not lie with the `when` renderer but rather the application code.

**Comment by sophypal** [comment] 2017-11-01 16:39
It's been a known issue for a while and I just never advertised what the issue was. It's not just isolated to the `when` renderer. There are certain states that can't be store easily in the form value. For instance, the selection of `Now` or a manual date value. That selection can't be initialized because the `date-time-picker` doesn't have a selection property. The bigger issue here is that it's not obvious or elegant to store component state like that in the form value.

**Comment by notmessenger** [comment] 2017-11-01 16:42
I will absolutely defer to your understanding of this issue and problem @sophypal.  That being said, doesn't the `frost-date-time-picker` have the ability to have its value set on it - https://github.com/ciena-frost/ember-frost-date-picker/issues/72#issuecomment-340557661 ?

**Comment by sophypal** [comment] 2017-11-01 16:45
That's my bad. The selection state is actually a part of the `when` renderer, not the `frost-date-time-picker`.

**Comment by sophypal** [comment] 2017-11-01 17:00
@d-ashfield, short term I think I can have it re-render on the date time selection vs the now. Will that be a good short term solution?

**Comment by d-ashfield** [comment] 2017-11-01 17:47
If we can find a way not to lose a selected date/time on a re-render that would be great.  It's one of the reasons we've erred to using the conditional-input-renderer even for some of the simple condition cases.

**Comment by sophypal** [comment] 2017-12-05 17:14
Resolved with PR 485

**Closed by sophypal** 2017-12-05 17:14 UTC
